variable "cidr" {}
variable "env" {}
variable "public_subnets" {}
variable "availability_zone" {}
variable "web_subnets" {}
variable "app_subnets" {}
variable "db_subnets" {}
variable "default_vpc_cidr" {}
variable "default_vpc_id" {}
variable "default_rt_id" {}
